# Generated by Django 2.2.24 on 2022-11-25 00:44

from django.db import migrations

def copy_info_new_building(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    for flat in Flat.objects.all():
        if flat.construction_year >= 2015:
            flat.new_building = True
            flat.save()
        else:
            flat.new_building=False
            flat.save()




class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(copy_info_new_building)
    ]
