# Generated by Django 2.2.24 on 2022-12-01 00:02

from django.db import migrations


def copy_info_new_building(apps, schema_editor, ):
    Flat = apps.get_model("property", "Flat")
    Flat.objects.filter(construction_year__gte=2015).update(new_building=True)
    Flat.objects.filter(construction_year__lte=2015).update(new_building=False)


def move_backward(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    for flat in Flat.objects.all():
        flat.new_building = flat.new_building
        flat.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(copy_info_new_building, move_backward)
    ]
