# Generated by Django 2.2.24 on 2022-11-25 00:59

import phonenumbers
from django.db import migrations

def update_phones_numbers(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    numbers= Flat.objects.all()
    if numbers.exists():
        for number in numbers.iterator():
            if number.owners_phonenumber != "":
                clear_phone_number = phonenumbers.parse(number.owners_phonenumber,
                                                        region="RU")

                if phonenumbers.is_possible_number(
                        clear_phone_number) and phonenumbers.is_valid_number(
                        clear_phone_number):
                    number.owner_pure_phone = number.owners_phonenumber

            number.save()




class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(update_phones_numbers)
    ]
