# Generated by Django 2.2.24 on 2022-12-02 13:05

from django.db import migrations


def update_info_in_owner(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    Owner = apps.get_model("property", "Owner")

    owner_names = Flat.objects.all()
    if owner_names.exists():
        for update_owner in owner_names.iterator():
            Owner.objects.get_or_create(name=update_owner.owner)
            update_owner.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0009_owner'),
    ]

    operations = [
        migrations.RunPython(update_info_in_owner)
    ]
