# Generated by Django 2.2.24 on 2022-11-25 01:06

from django.db import migrations
def update_info_in_owner(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    Owner =apps.get_model("property","Owner")

    for update_owner in Flat.objects.all():
        Owner.objects.get_or_create(owner=update_owner.owner)
        update_owner.save()



class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_owner'),
    ]

    operations = [
        migrations.RunPython(update_info_in_owner)
    ]
