# Generated by Django 2.2.24 on 2022-11-25 01:17

from django.db import migrations

from django.db import migrations

def copy_from_flat_to_owner(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    Owner = apps.get_model("property", "Owner")

    for flat in Flat.objects.all():
        Owner.objects.get_or_create(owner=flat.owner,
                                    phonenumber=flat.owners_phonenumber,
                                    pure_phonenumber=flat.owner_pure_phone)
        flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20221125_0506'),
    ]

    operations = [
        migrations.RunPython(copy_from_flat_to_owner)
    ]
