# Generated by Django 2.2.24 on 2022-12-02 13:06

from django.db import migrations
def copy_from_flat_to_owner(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    Owner = apps.get_model("property", "Owner")
    phones=Flat.objects.all()
    if phones.exists():
        for flat in phones.iterator():
            Owner.objects.get_or_create(name=flat.owner,
                                        phonenumber=flat.owners_phonenumber,
                                        pure_phonenumber=flat.owner_pure_phone)
            flat.save()



class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20221202_1705'),
    ]

    operations = [
        migrations.RunPython(copy_from_flat_to_owner)
    ]
